### PR TITLE
Activate simd

### PR DESCRIPTION
**Pull request by adriendelsalle**
Description
---

- activate simd in `xtensor` adding macro definition `XTENSOR_USE_XSIMD` in tests
- bump versions of `xtensor` and `xtensor-python` to be able to use simd with `pyarray`/`pytensor`
- add `-march=native` flag to use the full capabilities of the hardware

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
This conflicts with the more generic #17 

Plus can you set the simd preprocessor macro in the `XtensorExtractor` par in `np-becnh` ? probably by setting distutils options...

**Comment by serge-sans-paille** [comment]
#17 merged, you can rebase on it!

**Comment by adriendelsalle** [comment]
Hey @serge-sans-paille
Rebase done.

Any hint to set the macro once ?

**Comment by serge-sans-paille** [comment]
Pass extra options here: https://github.com/serge-sans-paille/numpy-benchmarks/blob/master/numpy_benchmarks/np-bench#L158 probably `define_macros` as specified in https://docs.python.org/3/distutils/apiref.html#distutils.core.Extension

**Comment by adriendelsalle** [comment]
Thanks @serge-sans-paille 
I pushed the modification :)

**Comment by serge-sans-paille** [comment]
This failing because some kernels actually don't compile with `xsimd` on. For instance this check https://github.com/serge-sans-paille/numpy-benchmarks/blob/5c09448d045726b347e868756f9e1b004d0876ea/numpy_benchmarks/benchmarks/mandelbrot.cpp#L27 leads to vectorization issue, seemingly because `abs` returns a batch of complex

**Comment by serge-sans-paille** [comment]
Obsoleted by #18

**Pull request closed without merging**
