### PR TITLE
Improve README with output comments

### PR DESCRIPTION
**Pull request by serge-sans-paille**

### CODE REVIEW

**Comment by VictorRodriguez** [comment]
I forgot to mention. It is already merged in OpenBenchmarking and some people  are using it : 

https://openbenchmarking.org/test/pts/numpy-1.0.1

**Comment by serge-sans-paille** [comment]
cool! Did you need to change a lot of things? I'm planning to write a blogpost about this benchmark in the coming weeks...

**Comment by VictorRodriguez** [comment]
Not at all . However as you can see on the source code of the phoronix test I am running everything . It takes hours to finish . I wonder if you could point me to the most selective benchmarks you think might be interesting to run. The blog will be great for documentation

**Comment by serge-sans-paille** [comment]
On Sat, Apr 23, 2016 at 07:00:34AM -0700, Victor wrote:
> Not at all . However as you can see on the source code of the phoronix test I am running everything . It takes hours to finish . I wonder if you could point me to the most selective benchmarks you think might be interesting to run. The blog will be great for documentation 

Yeah, it's because some benchmarks are really slow in Python mode and
get tremendous speedup with pythran/numba etc compilers

**Comment by serge-sans-paille** [comment]
@VictorRodriguez If you want to maintain a slightly different version of this benchmark, you can start with this patch http://pastebin.com/ZRZg8D6p . I don't want to merge or create a branch for it as it does not match my needs for numpy-benchmarks, but I think that's what you want to do: make sure all individual benchmarks have a comparable weight!

**Pull request merged**
